#!/usr/bin/env ruby

$LOAD_PATH << '.'

require 'fileutils'
require 'uri'

require 'grabber/alexa'
require 'grabber/mailru'

class AnalyticsGrabber
	def initialize(url)
		@url = url
	end

	def run
		r = {
			:alexa => Alexa.new(@url).run,
			:mailru => MailRu.new(@url).run,
		}
	end
end

p AnalyticsGrabber.new('http://ria.ru/').run
